name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # - name: Build and publish
      #   run: |
      #     chmod +x gradlew
      #     ./gradlew :publish -Pversion=${GITHUB_REF##*/}-SNAPSHOT
      #     ./gradlew :publish -Pversion=$(git rev-parse --short "$GITHUB_SHA")
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}